/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    students: StudentAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'college-achievements': CollegeAchievement;
    'student-achievements': StudentAchievement;
    gallery: Gallery;
    events: Event;
    recruiters: Recruiter;
    'research-areas': ResearchArea;
    faculty: Faculty;
    publications: Publication;
    payments: Payment;
    students: Student;
    results: Result;
    inquiries: Inquiry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'college-achievements': CollegeAchievementsSelect<false> | CollegeAchievementsSelect<true>;
    'student-achievements': StudentAchievementsSelect<false> | StudentAchievementsSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    recruiters: RecruitersSelect<false> | RecruitersSelect<true>;
    'research-areas': ResearchAreasSelect<false> | ResearchAreasSelect<true>;
    faculty: FacultySelect<false> | FacultySelect<true>;
    publications: PublicationsSelect<false> | PublicationsSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    students: StudentsSelect<false> | StudentsSelect<true>;
    results: ResultsSelect<false> | ResultsSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    about: About;
    contact: Contact;
    admissions: Admission;
    'campus-settings': CampusSetting;
    'placements-settings': PlacementsSetting;
    'home-settings': HomeSetting;
  };
  globalsSelect: {
    about: AboutSelect<false> | AboutSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
    admissions: AdmissionsSelect<false> | AdmissionsSelect<true>;
    'campus-settings': CampusSettingsSelect<false> | CampusSettingsSelect<true>;
    'placements-settings': PlacementsSettingsSelect<false> | PlacementsSettingsSelect<true>;
    'home-settings': HomeSettingsSelect<false> | HomeSettingsSelect<true>;
  };
  locale: null;
  user: User | Student;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface StudentAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "college-achievements".
 */
export interface CollegeAchievement {
  id: number;
  title: string;
  description: string;
  category: string;
  date: string;
  color?:
    | (
        | 'from-purple-500 to-pink-500'
        | 'from-blue-500 to-cyan-500'
        | 'from-yellow-500 to-orange-500'
        | 'from-green-500 to-emerald-500'
        | 'from-red-500 to-rose-500'
      )
    | null;
  iconType?: ('trophy' | 'award' | 'ranking' | 'target' | 'microscope') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "student-achievements".
 */
export interface StudentAchievement {
  id: number;
  title: string;
  description: string;
  studentName: string;
  category?: ('Technical' | 'Cultural' | 'Sports' | 'Research') | null;
  date?: string | null;
  prize?: string | null;
  color?: string | null;
  iconType?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  title: string;
  description?: string | null;
  date?: string | null;
  category: 'infrastructure' | 'events' | 'achievements';
  image: number | Media;
  alt: string;
  span?: ('md:col-span-1' | 'md:col-span-2' | 'md:col-span-2 md:row-span-2') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  description: string;
  category: 'Academic' | 'Cultural' | 'Sports';
  date: string;
  time: string;
  location: string;
  capacity?: string | null;
  registrationDeadline?: string | null;
  iconType?: ('laptop' | 'music' | 'microscope' | 'trophy' | 'palette') | null;
  color?:
    | (
        | 'from-blue-500 to-cyan-500'
        | 'from-purple-500 to-pink-500'
        | 'from-green-500 to-emerald-500'
        | 'from-orange-500 to-red-500'
        | 'from-pink-500 to-rose-500'
      )
    | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recruiters".
 */
export interface Recruiter {
  id: number;
  name: string;
  industry?: string | null;
  logo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-areas".
 */
export interface ResearchArea {
  id: number;
  title: string;
  description: string;
  iconType?: ('cpu' | 'heart' | 'leaf' | 'rocket' | 'zap' | 'globe') | null;
  colorTheme?:
    | (
        | 'from-blue-500 to-cyan-500'
        | 'from-red-500 to-rose-500'
        | 'from-green-500 to-emerald-500'
        | 'from-purple-500 to-indigo-500'
        | 'from-amber-500 to-orange-500'
      )
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faculty".
 */
export interface Faculty {
  id: number;
  name: string;
  title: string;
  specialty?: string | null;
  image: number | Media;
  researchArea?: (number | null) | ResearchArea;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications".
 */
export interface Publication {
  id: number;
  title: string;
  journal: string;
  publishDate?: string | null;
  link?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  student: number | Student;
  amount: number;
  category: 'tuition' | 'exam' | 'hostel';
  status?: ('pending' | 'paid') | null;
  paymentDate?: string | null;
  transactionId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "students".
 */
export interface Student {
  id: number;
  name: string;
  enrollmentNumber: string;
  phoneNumber: string;
  course: 'bca' | 'bba';
  needsPasswordChange?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'students';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "results".
 */
export interface Result {
  id: number;
  student: number | Student;
  semester: number;
  sgpa: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  name: string;
  email: string;
  phone: string;
  course: 'bca' | 'bba';
  lastQualification: string;
  message?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'college-achievements';
        value: number | CollegeAchievement;
      } | null)
    | ({
        relationTo: 'student-achievements';
        value: number | StudentAchievement;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'recruiters';
        value: number | Recruiter;
      } | null)
    | ({
        relationTo: 'research-areas';
        value: number | ResearchArea;
      } | null)
    | ({
        relationTo: 'faculty';
        value: number | Faculty;
      } | null)
    | ({
        relationTo: 'publications';
        value: number | Publication;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'students';
        value: number | Student;
      } | null)
    | ({
        relationTo: 'results';
        value: number | Result;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'students';
        value: number | Student;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'students';
        value: number | Student;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "college-achievements_select".
 */
export interface CollegeAchievementsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  category?: T;
  date?: T;
  color?: T;
  iconType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "student-achievements_select".
 */
export interface StudentAchievementsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  studentName?: T;
  category?: T;
  date?: T;
  prize?: T;
  color?: T;
  iconType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  title?: T;
  description?: T;
  date?: T;
  category?: T;
  image?: T;
  alt?: T;
  span?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  category?: T;
  date?: T;
  time?: T;
  location?: T;
  capacity?: T;
  registrationDeadline?: T;
  iconType?: T;
  color?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recruiters_select".
 */
export interface RecruitersSelect<T extends boolean = true> {
  name?: T;
  industry?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-areas_select".
 */
export interface ResearchAreasSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  iconType?: T;
  colorTheme?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faculty_select".
 */
export interface FacultySelect<T extends boolean = true> {
  name?: T;
  title?: T;
  specialty?: T;
  image?: T;
  researchArea?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications_select".
 */
export interface PublicationsSelect<T extends boolean = true> {
  title?: T;
  journal?: T;
  publishDate?: T;
  link?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  student?: T;
  amount?: T;
  category?: T;
  status?: T;
  paymentDate?: T;
  transactionId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "students_select".
 */
export interface StudentsSelect<T extends boolean = true> {
  name?: T;
  enrollmentNumber?: T;
  phoneNumber?: T;
  course?: T;
  needsPasswordChange?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "results_select".
 */
export interface ResultsSelect<T extends boolean = true> {
  student?: T;
  semester?: T;
  sgpa?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  course?: T;
  lastQualification?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  hero?: {
    year?: string | null;
    description?: string | null;
  };
  visionMission?: {
    vision?: {
      description?: string | null;
      points?:
        | {
            point?: string | null;
            id?: string | null;
          }[]
        | null;
    };
    mission?: {
      description?: string | null;
      points?:
        | {
            point?: string | null;
            id?: string | null;
          }[]
        | null;
    };
  };
  trustees?:
    | {
        name: string;
        title?: string | null;
        message?: string | null;
        qualification?: string | null;
        experience?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  faculty?: {
    description?: string | null;
    additional?: string | null;
    stats?:
      | {
          value?: string | null;
          label?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  contactInfo?:
    | {
        title: string;
        details?:
          | {
              line?: string | null;
              id?: string | null;
            }[]
          | null;
        action?: string | null;
        link?: string | null;
        color?:
          | (
              | 'from-blue-500 to-cyan-500'
              | 'from-green-500 to-emerald-500'
              | 'from-purple-500 to-pink-500'
              | 'from-orange-500 to-red-500'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admissions".
 */
export interface Admission {
  id: number;
  highlights?:
    | {
        label: string;
        value: string;
        iconType?: ('graduation' | 'users' | 'trophy' | 'clock') | null;
        id?: string | null;
      }[]
    | null;
  timeline?:
    | {
        step?: string | null;
        title?: string | null;
        description?: string | null;
        color?: string | null;
        id?: string | null;
      }[]
    | null;
  deadlines?: {
    undergraduate?:
      | {
          type?: string | null;
          deadline?: string | null;
          notification?: string | null;
          id?: string | null;
        }[]
      | null;
    graduate?:
      | {
          type?: string | null;
          deadline?: string | null;
          notification?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campus-settings".
 */
export interface CampusSetting {
  id: number;
  stats?:
    | {
        count?: string | null;
        label?: string | null;
        iconType?: ('users' | 'dumbbell' | 'heart' | 'palette') | null;
        id?: string | null;
      }[]
    | null;
  facilities?:
    | {
        category?: string | null;
        items?:
          | {
              name?: string | null;
              description?: string | null;
              iconType?:
                | ('library' | 'building' | 'home' | 'utensils' | 'coffee' | 'dumbbell' | 'music' | 'palette')
                | null;
              features?:
                | {
                    feature?: string | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  amenities?:
    | {
        label?: string | null;
        description?: string | null;
        iconType?: ('wifi' | 'shield' | 'wind' | 'calendar' | 'clock' | 'star') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "placements-settings".
 */
export interface PlacementsSetting {
  id: number;
  stats?:
    | {
        value: string;
        label: string;
        iconType?: ('trending' | 'dollar' | 'award' | 'building') | null;
        id?: string | null;
      }[]
    | null;
  highlights?:
    | {
        title: string;
        count: string;
        description: string;
        iconType?: ('award' | 'briefcase' | 'map-pin') | null;
        colorTheme?:
          | ('from-yellow-500 to-orange-500' | 'from-blue-500 to-cyan-500' | 'from-green-500 to-emerald-500')
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Add the companies that frequently recruit from our campus.
   */
  recruiters?:
    | {
        name: string;
        industry: string;
        /**
         * Optional: Upload the company logo.
         */
        logo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-settings".
 */
export interface HomeSetting {
  id: number;
  slides?:
    | {
        title: string;
        highlight: string;
        subtitle: string;
        description: string;
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  sanskritQuote?: string | null;
  quoteTranslation?: string | null;
  stats?:
    | {
        value: string;
        label: string;
        description?: string | null;
        color?: ('from-blue-500 to-cyan-500' | 'from-green-500 to-emerald-500' | 'from-purple-500 to-pink-500') | null;
        id?: string | null;
      }[]
    | null;
  courses?:
    | {
        courseKey: 'bca' | 'bba';
        title: string;
        shortTitle: string;
        description: string;
        duration?: string | null;
        totalCredits?: number | null;
        eligibility?: string | null;
        careers?:
          | {
              role?: string | null;
              id?: string | null;
            }[]
          | null;
        semesters?:
          | {
              semesterName: string;
              subjects?:
                | {
                    code?: string | null;
                    name: string;
                    credits?: number | null;
                    type?: string | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  testimonials?:
    | {
        name: string;
        role: string;
        quote: string;
        id?: string | null;
      }[]
    | null;
  mapUrl?: string | null;
  address?: string | null;
  /**
   * Highlight the key benefits of Avirat BBA & BCA College (Location, Faculty, etc.)
   */
  whyChooseUs?:
    | {
        title: string;
        description: string;
        iconType?: ('MapPin' | 'Wind' | 'Briefcase' | 'Users' | 'Cpu' | 'ShieldCheck' | 'Sparkles' | 'Building') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        year?: T;
        description?: T;
      };
  visionMission?:
    | T
    | {
        vision?:
          | T
          | {
              description?: T;
              points?:
                | T
                | {
                    point?: T;
                    id?: T;
                  };
            };
        mission?:
          | T
          | {
              description?: T;
              points?:
                | T
                | {
                    point?: T;
                    id?: T;
                  };
            };
      };
  trustees?:
    | T
    | {
        name?: T;
        title?: T;
        message?: T;
        qualification?: T;
        experience?: T;
        image?: T;
        id?: T;
      };
  faculty?:
    | T
    | {
        description?: T;
        additional?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  contactInfo?:
    | T
    | {
        title?: T;
        details?:
          | T
          | {
              line?: T;
              id?: T;
            };
        action?: T;
        link?: T;
        color?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admissions_select".
 */
export interface AdmissionsSelect<T extends boolean = true> {
  highlights?:
    | T
    | {
        label?: T;
        value?: T;
        iconType?: T;
        id?: T;
      };
  timeline?:
    | T
    | {
        step?: T;
        title?: T;
        description?: T;
        color?: T;
        id?: T;
      };
  deadlines?:
    | T
    | {
        undergraduate?:
          | T
          | {
              type?: T;
              deadline?: T;
              notification?: T;
              id?: T;
            };
        graduate?:
          | T
          | {
              type?: T;
              deadline?: T;
              notification?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campus-settings_select".
 */
export interface CampusSettingsSelect<T extends boolean = true> {
  stats?:
    | T
    | {
        count?: T;
        label?: T;
        iconType?: T;
        id?: T;
      };
  facilities?:
    | T
    | {
        category?: T;
        items?:
          | T
          | {
              name?: T;
              description?: T;
              iconType?: T;
              features?:
                | T
                | {
                    feature?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  amenities?:
    | T
    | {
        label?: T;
        description?: T;
        iconType?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "placements-settings_select".
 */
export interface PlacementsSettingsSelect<T extends boolean = true> {
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        iconType?: T;
        id?: T;
      };
  highlights?:
    | T
    | {
        title?: T;
        count?: T;
        description?: T;
        iconType?: T;
        colorTheme?: T;
        id?: T;
      };
  recruiters?:
    | T
    | {
        name?: T;
        industry?: T;
        logo?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-settings_select".
 */
export interface HomeSettingsSelect<T extends boolean = true> {
  slides?:
    | T
    | {
        title?: T;
        highlight?: T;
        subtitle?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  sanskritQuote?: T;
  quoteTranslation?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        description?: T;
        color?: T;
        id?: T;
      };
  courses?:
    | T
    | {
        courseKey?: T;
        title?: T;
        shortTitle?: T;
        description?: T;
        duration?: T;
        totalCredits?: T;
        eligibility?: T;
        careers?:
          | T
          | {
              role?: T;
              id?: T;
            };
        semesters?:
          | T
          | {
              semesterName?: T;
              subjects?:
                | T
                | {
                    code?: T;
                    name?: T;
                    credits?: T;
                    type?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  testimonials?:
    | T
    | {
        name?: T;
        role?: T;
        quote?: T;
        id?: T;
      };
  mapUrl?: T;
  address?: T;
  whyChooseUs?:
    | T
    | {
        title?: T;
        description?: T;
        iconType?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}